### ISSUE TITLE
Implement a caching system for when EasyRoom goes offline

### ISSUE THREAD

**Issue by xates** [matteocontrini/locuspocusbot#5]
It's been a couple times already that EasyRoom has gone offline. It would be good to implement a caching system so that when it does, the bot uses the last version from the cache, instead of just stop working.
A cache always containing the latest information for one week forward should be more than enough to cover even the longest black-out.

**Comment by matteocontrini** [comment]
Ciao.

>the bot uses the last version from the cache

La cache c'è già, aggiornata ogni ora, il problema è che quando una richiesta di aggiornamento fallisce il processo termina e la cache viene persa:

https://github.com/matteocontrini/locuspocusbot/blob/0961b0da6419d5a272997ea8c604f0948166daca/rooms.go#L137-L139

In un mondo ideale prima di mandare in produzione il bot avrei sostituito tutti i `panic()` con un `log.Fatal()` (o simile, non ricordo).

>A cache always containing the latest information for one week forward

La API di occupazione delle aule di EasyRoom permette di richiedere un giorno alla volta, quindi è da vedere.

Se hai voglia di migliorare qualcosa...
